### ISSUE TITLE
/first-pull-request error on fresh install

### ISSUE THREAD

**Issue by BenJam** [librariesio/libraries.io#1104]
Following the steps in README.md on macOS Sierra, I have a vanilla install working, all tests passing and services running. 

Navigating to /first-pull-request results in 

`Elasticsearch::Transport::Transport::Errors::BadRequest in GithubIssuesController#first_pull_request`

full error
```
[400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[Kuksk1QzS-uAO9A54EnUIg][github_issues][0]: SearchParseException[[github_issues][0]: query[function score (ConstantScore(BooleanFilter(+cache(state:open) +cache(locked:false) -cache(labels:wontfix) cache(labels:good first bug) cache(labels:good first contribution) cache(labels:good-first-bug) cache(labels:first-timers-only) cache(labels:good first issue) cache(labels:good first task) cache(labels:easy first bug) cache(labels:your first pr) cache(labels:firstbug) cache(labels:good-first-pr) cache(labels:[Type] Good First Bug) cache(labels:good first patch) cache(labels:first bug) cache(labels:good first step) cache(labels:good-first-issue) cache(labels:IdealFirstBug) cache(labels:first contribution) cache(labels:first timers only) cache(labels:your-first-pr) cache(labels:starter) cache(labels:beginner) cache(labels:easy) cache(labels:E-easy))),function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@69a939b0)],from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"function_score\":{\"query\":{\"filtered\":{\"query\":{\"match_all\":{}},\"filter\":{\"bool\":{\"must\":[{\"term\":{\"state\":\"open\"}},{\"term\":{\"locked\":false}}],\"must_not\":[{\"term\":{\"labels\":\"wontfix\"}}],\"should\":[{\"term\":{\"labels\":\"good first bug\"}},{\"term\":{\"labels\":\"good first contribution\"}},{\"term\":{\"labels\":\"good-first-bug\"}},{\"term\":{\"labels\":\"first-timers-only\"}},{\"term\":{\"labels\":\"good first issue\"}},{\"term\":{\"labels\":\"good first task\"}},{\"term\":{\"labels\":\"easy first bug\"}},{\"term\":{\"labels\":\"your first pr\"}},{\"term\":{\"labels\":\"firstbug\"}},{\"term\":{\"labels\":\"good-first-pr\"}},{\"term\":{\"labels\":\"[Type] Good First Bug\"}},{\"term\":{\"labels\":\"good first patch\"}},{\"term\":{\"labels\":\"first bug\"}},{\"term\":{\"labels\":\"good first step\"}},{\"term\":{\"labels\":\"good-first-issue\"}},{\"term\":{\"labels\":\"IdealFirstBug\"}},{\"term\":{\"labels\":\"first contribution\"}},{\"term\":{\"labels\":\"first timers only\"}},{\"term\":{\"labels\":\"your-first-pr\"}},{\"term\":{\"labels\":\"starter\"}},{\"term\":{\"labels\":\"beginner\"}},{\"term\":{\"labels\":\"easy\"}},{\"term\":{\"labels\":\"E-easy\"}}]}}}},\"field_value_factor\":{\"field\":\"stars\",\"modifier\":\"square\"}}},\"facets\":{\"language\":{\"terms\":{\"field\":\"language\",\"size\":35},\"facet_filter\":{\"bool\":{\"must\":[]}}},\"labels\":{\"terms\":{\"field\":\"labels\",\"size\":35},\"facet_filter\":{\"bool\":{\"must\":[]}}},\"license\":{\"terms\":{\"field\":\"license\",\"size\":35},\"facet_filter\":{\"bool\":{\"must\":[]}}}},\"filter\":{\"bool\":{\"must\":[],\"must_not\":[]}},\"track_scores\":true,\"sort\":[{\"comments_count\":\"asc\"},{\"stars\":\"desc\"},{\"created_at\":\"asc\"},{\"contributions_count\":\"asc\"}]}]]]; nested: SearchParseException[[github_issues][0]: query[function score (ConstantScore(BooleanFilter(+cache(state:open) +cache(locked:false) -cache(labels:wontfix) cache(labels:good first bug) cache(labels:good first contribution) cache(labels:good-first-bug) cache(labels:first-timers-only) cache(labels:good first issue) cache(labels:good first task) cache(labels:easy first bug) cache(labels:your first pr) cache(labels:firstbug) cache(labels:good-first-pr) cache(labels:[Type] Good First Bug) cache(labels:good first patch) cache(labels:first bug) cache(labels:good first step) cache(labels:good-first-issue) cache(labels:IdealFirstBug) cache(labels:first contribution) cache(labels:first timers only) cache(labels:your-first-pr) cache(labels:starter) cache(labels:beginner) cache(labels:easy) cache(labels:E-easy))),function=org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction@69a939b0)],from[-1],size[-1]: Parse Failure [No mapping found for [comments_count] in order to sort on]]; }]","status":400}
```

extracted source
```
def first_pull_request_issues(labels)
    @search = paginate GithubIssue.first_pr_search(filters: {
      license: current_license,
      language: current_language,
      labels: labels
```

full stack trace:

```
elasticsearch-transport (1.1.0) lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
elasticsearch-transport (1.1.0) lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
elasticsearch-transport (1.1.0) lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
elasticsearch-transport (1.1.0) lib/elasticsearch/transport/client.rb:128:in `perform_request'
elasticsearch-api (1.1.0) lib/elasticsearch/api/actions/search.rb:175:in `search'
elasticsearch-model (0.1.9) lib/elasticsearch/model/searching.rb:51:in `execute!'
elasticsearch-model (0.1.9) lib/elasticsearch/model/response.rb:31:in `response'
elasticsearch-model (0.1.9) lib/elasticsearch/model/response/base.rb:33:in `total'
elasticsearch-model (0.1.9) lib/elasticsearch/model/response/pagination.rb:177:in `total_entries'
will_paginate (3.1.5) lib/will_paginate/collection.rb:16:in `total_pages'
will_paginate (3.1.5) lib/will_paginate/collection.rb:26:in `next_page'
api-pagination (4.5.2) lib/api-pagination/configuration.rb:101:in `last_page?'
api-pagination (4.5.2) lib/api-pagination.rb:28:in `block in pages_from'
api-pagination (4.5.2) lib/api-pagination.rb:22:in `tap'
api-pagination (4.5.2) lib/api-pagination.rb:22:in `pages_from'
api-pagination (4.5.2) lib/rails/pagination.rb:34:in `_paginate_collection'
api-pagination (4.5.2) lib/rails/pagination.rb:9:in `paginate'
app/controllers/application_controller.rb:117:in `first_pull_request_issues'
app/controllers/github_issues_controller.rb:13:in `first_pull_request'
actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
sql_queries_count (0.0.1) lib/sql_queries_count/controller_runtime.rb:14:in `process_action'
actionpack (5.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.2) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.2) lib/omniauth/builder.rb:63:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack-attack-rate-limit (1.1.0) lib/rack/attack/rate-limit.rb:22:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack-attack (5.0.1) lib/rack/attack.rb:147:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:25:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activerecord (5.0.1) lib/active_record/migration.rb:553:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:122:in `block in call'
rack-timeout (0.4.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.4.2) lib/rack/timeout/core.rb:121:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (5.0.1) lib/rails/engine.rb:522:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
puma (3.6.2) lib/puma/configuration.rb:225:in `call'
puma (3.6.2) lib/puma/server.rb:578:in `handle_request'
puma (3.6.2) lib/puma/server.rb:415:in `process_client'
puma (3.6.2) lib/puma/server.rb:275:in `block in run'
puma (3.6.2) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by andrew** [comment]
`[No mapping found for [comments_count] in order to sort on]` is the issue here, investigating why you get it but I don't

**Comment by andrew** [comment]
Should be fixed by https://github.com/librariesio/libraries.io/commit/586c6bdc31a4c14d4036b4706a5153ceb2f2a285
