### ISSUE TITLE
Example of Policy Role may need UpdataShardCount action allowed 

### ISSUE THREAD

**Issue by thiagofborn** [librariesio/libraries.io#2132]
Hello, 

I am totally sure if the project does not cover the possibility of "Updating the shard count".

But in case you agree, the policy role example needs a small change. As follows:

From: 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kinesis:Get*",
                "kinesis:List*",
                "kinesis:Describe*",
                "kinesis:MergeShards",
                "kinesis:SplitShard"
            ],
            "Resource": "*"
        },
        {
            "Action": [
                "sns:Publish"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:sns:us-east-1:01234567890:scaling-test-notification"
        },
        {
            "Action": [
                "cloudwatch:GetMetricStatistics"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::config-bucket-goes-here/*"
        }
    ]
}
```
To: 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kinesis:Get*",
                "kinesis:List*",
                "kinesis:Describe*",
                "kinesis:MergeShards",
                "kinesis:UpdateShardCount",
                "kinesis:SplitShard"
            ],
            "Resource": "*"
        },
        {
            "Action": [
                "sns:Publish"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:sns:us-east-1:01234567890:scaling-test-notification"
        },
        {
            "Action": [
                "cloudwatch:GetMetricStatistics"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": "arn:aws:s3:::config-bucket-goes-here/*"
        }
    ]
}
```

Otherwise you will get:
```java
SEVERE [pool-1-thread-1] com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics Failed to process stream java_dev
 com.amazonaws.services.kinesis.model.AmazonKinesisException: User: arn:aws:sts::my_account_id:assumed-role/aws-elasticbeanstalk-ec2-role/i-my_instance_id is not authorized to perform: kinesis:UpdateShardCount on resource: arn:aws:kinesis:eu-west-1:my_account_id:stream/my_stream_dev (Service: AmazonKinesis; Status Code: 400; Error Code: AccessDeniedException; Request ID: my_request_id)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1592)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeUpdateShardCount(AmazonKinesisClient.java:2159)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.updateShardCount(AmazonKinesisClient.java:2135)
	at com.amazonaws.services.kinesis.scaling.StreamScaler.updateShardCount(StreamScaler.java:477)
	at com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.processCloudwatchMetrics(StreamMonitor.java:308)
	at com.amazonaws.services.kinesis.scaling.auto.StreamMonitor.run(StreamMonitor.java:379)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by katzj** [comment]
This looks like it should be filed against the repository that you're talking about and not libraries.io which is just aggregating that information
