### ISSUE TITLE
NameError: uninitialized constant Issue after rake search:reindex_everything

### ISSUE THREAD

**Issue by besendorf** [librariesio/libraries.io#2815]
When following the installation instructions for a development (https://github.com/librariesio/libraries.io/blob/main/docs/development-setup.md) and executing ``` rake search:reindex_everything``` The following error is returned:
On Debian Buster with rvm 2.6.5 and ElasticSearch 2.4
```
$ rake search:reindex_everything --trace
** Invoke search:reindex_everything (first_time)
** Invoke search:reindex_repos (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke search:recreate_repos_index (first_time)
** Invoke environment
** Execute search:recreate_repos_index
[!!!] Index does not exist (Elasticsearch::Transport::Transport::Errors::NotFound)
** Execute search:reindex_repos
** Invoke search:reindex_issues (first_time)
** Invoke environment
** Invoke search:recreate_issues_index (first_time)
** Invoke environment
** Execute search:recreate_issues_index
rake aborted!
NameError: uninitialized constant Issue
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
/home/user/libraries.io/lib/tasks/search.rake:22:in `block (2 levels) in <main>'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
NameError: uninitialized constant Issue
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/home/user/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/home/user/libraries.io/lib/tasks/search.rake:22:in `block (2 levels) in <main>'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/home/user/.rvm/gems/ruby-2.6.5/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.6.5/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => search:reindex_everything => search:reindex_issues => search:recreate_issues_index
```

**Comment by tiegz** [comment]
Thanks, should be fixed now!

**Comment by besendorf** [comment]
Tahnk you very much. Works now
